//I am changing the image links from firebase to amazon, firebase has issues with these direct links. Please remember to add the amazon link(that will show up at the error) instead of firebase at the cofig for it to work out.

export const products = [
  {
    id: '64a654593e91b8e73a351e9b',
    title: 'iphone 14',
    quantity: 2,
    description: 'Short description',
    price: 2999,
    brand: 'Apple',
    category: 'smartphones',
    inStock: true,
    images: [
      {
        color: 'White',
        colorCode: '#FFFFFF',
        image:
          'https://m.media-amazon.com/images/I/71p-tHQ0u1L._AC_SX679_.jpg',
        alt: 'iphone 14 - Image 0',
      },
      {
        color: 'Gray',
        colorCode: '#808080',
        image:
          'https://m.media-amazon.com/images/I/417tEj3iJ8L._AC_.jpg',
        alt: 'iphone 14 - Image 1',
      },
    ],
    reviews: [],
  },
  {
    id: '64a4ebe300900d44bb50628a',
    title:
      'Logitech MX Keys Advanced Wireless Illuminated Keyboard, Tactile Responsive Typing, Backlighting, Bluetooth, USB-C, Apple macOS, Microsoft Windows, Linux, iOS, Android, Metal Build (Black)',
    description:
      'PERFECT STROKE KEYS - Spherically-dished keys match the shape of your fingertips, offering satisfying feedback with every tap\nCOMFORT AND STABILITY - Type with confidence on a keyboard crafted for comfort, stability, and precision',
    price: 102.99,
    brand: 'Logitech',
    category: 'accessories',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image:
          'https://m.media-amazon.com/images/I/71gOLg2-kqL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        alt: 'Logitech MX Keys Advanced Wireless Illuminated Keyboard, Tactile Responsive Typing, Backlighting, Bluetooth, USB-C, Apple macOS, Microsoft Windows, Linux, iOS, Android, Metal Build (Black) - Image 0',
      },
    ],
    reviews: [
      {
        id: '64a65a6158b470c6e06959ee',
        userId: '6475af156bad4917456e6e1e',
        productId: '64a4ebe300900d44bb50628a',
        rating: 5,
        comment: 'good',
        createdDate: '2023-07-06T06:08:33.067Z',
        user: {
          id: '6475af156bad4917456e6e1e',
          name: 'Charles',
          email: 'example@gmail.com',
          emailVerified: null,
          image:
            'https://lh3.googleusercontent.com/a/AAcHTteOiCtILLBWiAoolIW9PJH-r5825pBDl824_8LD=s96-c',
          hashedPassword: null,
          createdAt: '2023-05-30T08:08:53.979Z',
          updatedAt: '2023-05-30T08:08:53.979Z',
          role: 'ADMIN',
        },
      },
    ],
  },
  {
    id: '648437b38c44d52b9542e340',
    title: 'Apple iPhone 13, 64GB',
    description:
      'The product is refurbished, fully functional, and in excellent condition. Backed by the 90-day E~Shop Renewed Guarantee.\n- This pre-owned product has been professionally inspected, tested and cleaned by Amazon qualified vendors. It is not certified by Apple.\n- This product is in "Excellent condition". The screen and body show no signs of cosmetic damage visible from 12 inches away.\n- This product will have a battery that exceeds 80% capacity relative to new.\n- Accessories may not be original, but will be compatible and fully functional. Product may come in generic box.\n- Product will come with a SIM removal tool, a charger and a charging cable. Headphone and SIM card are not included.\n- This product is eligible for a replacement or refund within 90-day of receipt if it does not work as expected.\n- Refurbished phones are not guaranteed to be waterproof.',
    price: 40,
    brand: 'Apple',
    category: 'smartphones',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image:
          'https://m.media-amazon.com/images/I/61g+McQpg7L._AC_SX679_.jpg',
        alt: 'Apple iPhone 13, 64GB - Image 0',
      },
      {
        color: 'Blue',
        colorCode: ' #0000FF',
        image:
          'https://m.media-amazon.com/images/I/713Om9vCHUL._AC_SX679_.jpg',
        alt: 'Apple iPhone 13, 64GB - Image 1',
      },
      {
        color: 'Red',
        colorCode: '#FF0000',
        image:
          'https://m.media-amazon.com/images/I/61thdjmfHcL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        alt: 'Apple iPhone 13, 64GB - Image 2',
      },
    ],
    reviews: [
      {
        id: '6499b4887402b0efd394d8f3',
        userId: '6499b184b0e9a8c8709821d3',
        productId: '648437b38c44d52b9542e340',
        rating: 4,
        comment:
          'good enough. I like the camera and casing. the delivery was fast too.',
        createdDate: '2023-06-26T15:53:44.483Z',
        user: {
          id: '6499b184b0e9a8c8709821d3',
          name: 'Chaoo',
          email: 'example1@gmail.com',
          emailVerified: null,
          image:
            'https://lh3.googleusercontent.com/a/AAcHTtcuRLwWi1vPKaQOcJlUurlhRAIIq2LgYccE8p32=s96-c',
          hashedPassword: null,
          createdAt: '2023-06-26T15:40:52.558Z',
          updatedAt: '2023-06-26T15:40:52.558Z',
          role: 'USER',
        },
      },
      {
        id: '6499a110efe4e4de451c7edc',
        userId: '6475af156bad4917456e6e1e',
        productId: '648437b38c44d52b9542e340',
        rating: 5,
        comment: 'I really liked it!!',
        createdDate: '2023-06-26T14:30:40.998Z',
        user: {
          id: '6475af156bad4917456e6e1e',
          name: 'Charles',
          email: 'example@gmail.com',
          emailVerified: null,
          image:
            'https://lh3.googleusercontent.com/a/AAcHTteOiCtILLBWiAoolIW9PJH-r5825pBDl824_8LD=s96-c',
          hashedPassword: null,
          createdAt: '2023-05-30T08:08:53.979Z',
          updatedAt: '2023-05-30T08:08:53.979Z',
          role: 'ADMIN',
        },
      },
    ],
  },
  {
    id: '64a4e9e77e7299078334019f',
    title:
      'Logitech MX Master 2S Wireless Mouse – Use on Any Surface, Hyper-Fast Scrolling, Ergonomic Shape, Rechargeable, Control Upto 3 Apple Mac and Windows Computers, Graphite',
    description:
      'Cross computer control: Game changing capacity to navigate seamlessly on 3 computers, and copy paste text, images, and files from 1 to the other using Logitech flow\nDual connectivity: Use with upto 3 Windows or Mac computers via included Unifying receiver or Bluetooth Smart wireless technology. Gesture button- Yes',
    price: 70,
    quantity: 1,
    brand: 'logitech',
    category: 'accessories',
    inStock: true,
    images: [
      {
        color: 'Graphite',
        colorCode: ' #383838',
        image:
          'https://m.media-amazon.com/images/I/61ni3t1ryQL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        alt: 'Logitech MX Master 2S Wireless Mouse - Graphite - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497040',
    title:
      'Smart Watch(Answer/Make Call), 1.85" Smartwatch for Men Women IP68 Waterproof, 100+ Sport Modes, Fitness Activity Tracker, Heart Rate Sleep Monitor, Pedometer, Smart Watches for Android iOS, 2023',
    description:
      'Bluetooth Call and Message Reminder: The smart watch is equipped with HD speaker, after connecting to your phone via Bluetooth, you can directly use the smartwatches to answer or make calls, read messages, store contacts, view call history. The smartwatch can set up more message notifications in "GloryFit" APP. You will never miss any calls and messages during meetings, workout and riding.',
    price: 50,
    brand: 'Nerunsa',
    quantity: 1,
    category: 'womens-watches',
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image:
          'https://m.media-amazon.com/images/I/71s4mjiit3L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        alt: 'Nerunsa Smart Watch - Black - Image 0',
      },
      {
        color: 'Silver',
        colorCode: '#C0C0C0',
        image:
          'https://m.media-amazon.com/images/I/71zbWSRMaYL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        alt: 'Nerunsa Smart Watch - Silver - Image 1',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497041',
    title: 'Kimono & Caftan - Black - Casual',
    description: 'Kimono & Caftan',
    quantity: 1,
    price: 215,
    brand: 'Mango',
    category: 'womens-dresses',
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image: '/women-cloth-1.jpg',
        alt: 'Mango Kimono & Caftan - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497042',
    title: 'Midi atlas Slim fit - bohemian',
    quantity: 2,
    description: 'Midi atlas Slim fit',
    price: 125,
    brand: 'Uniqlo',
    category: 'womens-dresses',
    inStock: true,
    images: [
      {
        color: 'Blue',
        colorCode: '#000000',
        image: '/women-cloth-2.jpg',
        alt: 'Uniqlo Midi Atlas Slim fit - Bohemian - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497043',
    title: 'Kimono & Caftan - Black - Bohemain',
    description: 'Kimono & Caftan - Black - Bohemain',
    quantity: 1,
    price: 398,
    brand: 'Zara',
    category: 'womens-dresses',
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image: '/women-cloth-3.jpg',
        alt: 'Zara Kimono & Caftan - Black - Bohemian - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497044',
    title: 'Blouse - Minimalist',
    description: 'Blouse - Minimalist',
    price: 68,
    brand: 'Ralph Lauren',
    quantity: 1,
    category: 'tops',
    inStock: true,
    images: [
      {
        color: 'Green',
        colorCode: '#000000',
        image: '/women-cloth-4.jpg',
        alt: 'Ralph Lauren Blouse - Minimalist - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497045',
    title: 'Dress-Beige-Shift-Casual',
    description: 'Dress-Beige-Shift-Casual',
    price: 512,
    brand: 'Rachel Pally',
    quantity: 1,
    category: 'womens-dresses',
    inStock: true,
    images: [
      {
        color: 'Pink',
        colorCode: '#000000',
        image: '/women-cloth-5.jpg',
        alt: 'Rachel Pally Dress-Beige-Shift-Casual - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497046',
    title: 'Shirt-oversize-Minimalist',
    description: 'Shirt-oversize-Minimalist',
    price: 259,
    brand: 'Ralph Lauren',
    category: 'tops',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'White',
        colorCode: '#000000',
        image: '/women-cloth-6.jpg',
        alt: 'Ralph Lauren Shirt-oversize-Minimalist - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497047',
    title: 'Printed Dress',
    description: 'Printed Dress',
    price: 39.99,
    brand: 'Zara',
    category: 'womens-dresses',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'Orange',
        colorCode: '#000000',
        image: '/women-cloth-7.jpg',
        alt: 'Zara Printed Dress - Black - Casual - Image 0',
      },
      {
        color: 'Orange',
        colorCode: '#000000',
        image: '/women-cloth-7-1.jpg',
        alt: 'Zara Printed Dress - Black - Casual - Image 1',
      },
      {
        color: 'Orange',
        colorCode: '#000000',
        image: '/women-cloth-7-2.jpg',
        alt: 'Zara Printed Dress - Black - Casual - Image 2',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497048',
    title: 'Sweather - Black & White - Minimalist',
    description: 'Sweather - Black & White - Minimalist',
    price: 420,
    brand: 'Zara',
    category: 'tops',
    inStock: true,
    quantity: 1,
    images: [
      {
        color: 'white',
        colorCode: '#000000',
        image: '/women-cloth-8.jpg',
        alt: 'Zara Sweather - Black & White - Minimalist - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497057',
    title: 'Seather - Casual',
    description: 'Seather - Casual',
    price: 100,
    quantity: 1,
    brand: 'Uniqlo',
    category: 'womens-dresses',
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image: '/women-cloth-9.jpg',
        alt: 'Uniqlo Seather - Casual - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497049',
    title: 'Shoulder bag-White-Plain',
    description: 'Shoulder bag-White-Plain',
    quantity: 2,
    price: 69.99,
    brand: 'Tonny Black',
    category: 'womens-bags',
    inStock: true,
    images: [
      {
        color: 'Yellow',
        colorCode: '#000000',
        image: '/purse-1.jpg',
        alt: 'Tonny Black Shoulder bag-White-Plain - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497050',
    title: 'Shoulder bag-Pink-Plain',
    description: 'Shoulder bag-Pink-Plain',
    price: 69.99,
    brand: 'Patso',
    category: 'womens-bags',
    quantity: 0,
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image: '/purse-2.jpg',
        alt: 'Patso Shoulder bag-Pink-Plain - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497051',
    title: "Women's Powder Sneaker",
    description: "Women's Powder Sneaker",
    price: 112.02,
    brand: 'Reebok',
    category: 'womens-shoes',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'White',
        colorCode: '#000000',
        image: '/shoes-1.jpg',
        alt: "Reebok Women's Powder Sneaker - Black - Casual - Image 0",
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497052',
    title: 'Sport-shoe 2102',
    description: 'Sport-shoe 2102',
    price: 80,
    brand: 'Sketchers',
    quantity: 0,
    category: 'womens-shoes',
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image: '/shoes-2.jpg',
        alt: 'Sketchers Sport-shoe 2102 - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497053',
    title: 'INSTAX Wide 300 Black',
    description: 'INSTAX Wide 300 Black',
    price: 82.99,
    brand: 'INSTAX',
    category: 'accessories',
    inStock: true,
    quantity: 0,
    images: [
      {
        color: 'White',
        colorCode: '#000000',
        image: '/camera-1.jpg',
        alt: 'INSTAX Wide 300 Black - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497054',
    title: 'INSTAX Square SQ1 Chalk',
    description: 'INSTAX Square SQ1 Chalk',
    price: 112.99,
    brand: 'INSTANX',
    category: 'accessories',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'Beige',
        colorCode: '#000000',
        image: '/camera-2.jpg',
        alt: 'Polaroid Now Gen 2 Instant - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497055',
    title: 'Polaroid Now Gen 2 Instant',
    description: 'Polaroid Now Gen 2 Instant',
    price: 119.99,
    brand: 'Polaroid',
    quantity: 1,
    category: 'accessories',
    inStock: true,
    images: [
      {
        color: 'White',
        colorCode: '#000000',
        image: '/camera-3.jpg',
        alt: 'Polaroid Now Gen 2 Instant - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
  {
    id: '649d775128b6744f0f497056',
    title: 'INSTAX Wide 300 Black',
    description: 'INSTAX Wide 300 Black',
    price: 109,
    brand: 'INSTAX',
    category: 'accessories',
    quantity: 1,
    inStock: true,
    images: [
      {
        color: 'Black',
        colorCode: '#000000',
        image: '/camera-4.jpg',
        alt: 'INSTAX Wide 300 Black - Black - Casual - Image 0',
      },
    ],
    reviews: [],
  },
];
